### ISSUE TITLE
The menu sometimes does not close itself when changing UIViewControllers

### ISSUE THREAD

**Issue by jschmid** [erichoracek/MSDynamicsDrawerViewController#67] opened 2014-01-14 14:26 UTC
A video is worth a thousand words: http://www.youtube.com/watch?v=rOc5X-xuKuk

I am using an iPhone 4. Randomly, the menu opens wide and never closes again.

If you look at [this line](https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/16041b8fc2f944c68638d4d1588142e0a3cf598f/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m#L1262), I found that sometimes `paneViewIsPositionedInValidState` returns `NO` and `dynamicAnimatorDidPause` is never called again.
Hence, `self.dynamicAnimatorCompletion` is never called and the whole process fails.

It seems it needs more fine tuning but I am not able to see what should be done.

Note that if I set `paneViewSlideOffAnimationEnabled` to `NO` it works fine since there is no animation, but that's not what I want.

Any idea how to fix this? Thanks

**Comment by iltercengiz** [comment] 2014-01-14 14:39
Same here.

**Comment by erichoracek** [comment] 2014-01-14 17:39
I think I've figured out what causes this. If the user taps on the `paneView` _during_ the transition to a new pane view controller, it can get stuck in the open wide state. I'll see if I can figure out a way to prevent this.

**Comment by jschmid** [comment] 2014-01-15 08:45
I am not sure that I understand what you are saying, but you can see in my video that I do not tap the `paneView` before the menu gets stuck.
I tried now by touching everything I can while the menu is moving and it most often works as expected.

**Comment by erichoracek** [comment] 2014-01-16 21:30
Apologies, I totally missed the video—I see what you're talking about now and I have located the bug and the solution. It has to do with the work that I did to speed up the pane transition a few weeks ago. I'll work on geting a fix out ASAP. I think the bug that I was seeing was caused by the same issue as the one you documented.

**Comment by polaski** [comment] 2014-01-18 00:24
I've been experiencing the same problem a lot. Thank god I found this thread! When do you think the next release including this patch will be released?

**Comment by netoxico** [comment] 2014-01-20 16:43
I have the same problem. I reverted to version 1.2.1 and still having the same problem but looks like is less frequently.

**Comment by erichoracek** [comment] 2014-01-20 22:36
This should be fixed in version `1.3.1`. Update and let me know.

**Closed as completed by erichoracek** 2014-01-20 22:36 UTC

**Comment by netoxico** [comment] 2014-01-20 23:19
Updated to 1.3.1 and is now working with no problem.

**Comment by jschmid** [comment] 2014-01-21 07:41
Seems to be working fine for me.

Thanks ! :thumbsup:
