### ISSUE TITLE
Hidden status bar area

### ISSUE THREAD

**Issue by iltercengiz** [erichoracek/MSDynamicsDrawerViewController#80] opened 2014-01-28 13:53 UTC
Sometimes panes hide the status bar area, placing their navigation bar's to the top.
This screenshot will better describe the problem.

![screenshot](https://f.cloud.github.com/assets/1618181/2019449/4eafc466-8823-11e3-9881-dbb5111e5b25.png)

I tried to find the problem by debugging but couldn't come across to it.
As we're about to release the app, any suggestion to fix this or an update to the repo would be appreciated.

Thanks.

**Comment by erichoracek** [comment] 2014-01-29 16:52
This is an unfortunate issue that can be caused by the logic surrounding how the iOS7 SDK decides if it should have a status bar space present. However, in the example project, I have never encountered this issue as long as a few conditions are met. I can dig up a description of what causes this—for now are you using a `UINavigationController` as your `paneViewController`?

**Comment by iltercengiz** [comment] 2014-01-29 18:01
Yes, they are all `UINavigationController`s.

**Comment by erichoracek** [comment] 2014-01-29 18:26
[This blog post](http://blog.jaredsinclair.com/post/61507315630/wrestling-with-status-bars-and-navigation-bars-on-ios-7) gives a good description of the behavior—specifically point 4. Take a look and see if anything in there looks like it could be causing the issue.

**Comment by iltercengiz** [comment] 2014-01-29 18:36
Seems legit, but actually I first saw this behavior when I updated to version 1.4.0. Before this version I have never came across to this bug, so I couldn't be sure that this is absolutely a bug of iOS 7.

**Comment by sircharleswatson** [comment] 2014-02-05 15:19
I had this same issue and figured out that if you change the paneController to not go off-screen during its closing animation, it no longer has that effect.

**Comment by wangxinnong** [comment] 2014-04-19 16:27
I met the same issue. It can even be occur in your example project.
![snapshot](https://cloud.githubusercontent.com/assets/5747937/2748894/636902ea-c7df-11e3-8a8b-05f963de5dd6.png)

**Comment by wangxinnong** [comment] 2014-04-19 16:34
The solution does work: https://github.com/cloudkite/Masonry/issues/51

**Closed as completed** 2022-01-17 21:55 UTC
