### ISSUE TITLE
how can i disable the bounce effection ?

### ISSUE THREAD

**Issue by hufeng825** [erichoracek/MSDynamicsDrawerViewController#53] opened 2013-12-24 10:11 UTC
how can i disable the bounce effection ?

**Comment by nullproduction** [comment] 2013-12-24 10:57
Hello, this is impossible.
https://github.com/monospacecollective/MSDynamicsDrawerViewController/issues/32

**Comment by erichoracek** [comment] 2013-12-26 19:20
Duplicate of #32.

**Closed as completed by erichoracek** 2013-12-26 19:20 UTC
