### ISSUE TITLE
PanController twitches after open

### ISSUE THREAD

**Issue by kioqq** [erichoracek/MSDynamicsDrawerViewController#128] opened 2014-09-22 17:03 UTC
I love MSDynamicsDrawerViewController. But, this bug unnerving me :(
See on navigationBar in gif.

![dragpanecontroller](https://cloud.githubusercontent.com/assets/5331145/4360257/f59ceedc-4279-11e4-905c-9253f91e8c19.gif)

How fix this? :fire: 
Please, help me!

**Comment by lluisgerard** [comment] 2014-09-22 18:05
I know where is the problem but don't know exactly how to fix it yet, or why is it happening now on iOS 8. Because there has been always a little glitch when opening the panel, but on iOS 8 it also happens on closing and is very noticeable.

The problem comes from the `UICollisionBehavior`. This is what tells the panel where are the boundaries, and where to stop the animation.

If you search for this method inside the `MSDynamicsDrawerViewController.m` file:

```
- (UIBezierPath *)boundaryPathForState:(MSDynamicsDrawerPaneState)state direction:(MSDynamicsDrawerDirection)direction
```

You'll see this boundary definition:

```
   CGRect boundary = CGRectZero;
   boundary.origin = (CGPoint){-1.0, -1.0};
```

If you play with this, you'll see that you can fix the closing part (on iOS 8) changing it to -0.5 on the X:

```
boundary.origin = (CGPoint){-0.5, -1.0};
```

Why? I still don't know exactly, but I changed the method to play with it, adding plus1 and plus2 variables instead of the 1.0 and 2.0 hardcoded, because it should be the way the boundaries are calculated. Playing a little with this, on iOS 8 this is what gives me the best results:

```
    CGFloat plus1 = 1;
    CGFloat plus2 = 1;
    CGRect boundary = CGRectZero;
    boundary.origin = (CGPoint){-0.5, -0.5};
    if (self.possibleDrawerDirection & MSDynamicsDrawerDirectionHorizontal) {
        boundary.size.height = (CGRectGetHeight(self.paneView.frame) + plus1);
        switch (state) {
            case MSDynamicsDrawerPaneStateClosed:
                boundary.size.width = ((CGRectGetWidth(self.paneView.frame) * 2.0) + self.paneStateOpenWideEdgeOffset + plus2);
                break;
            case MSDynamicsDrawerPaneStateOpen:
                boundary.size.width = ((CGRectGetWidth(self.paneView.frame) + self.openStateRevealWidth) + plus2);
                break;
            case MSDynamicsDrawerPaneStateOpenWide:
                boundary.size.width = ((CGRectGetWidth(self.paneView.frame) * 2.0) + self.paneStateOpenWideEdgeOffset + plus2);
                break;
        }
    } else if (self.possibleDrawerDirection & MSDynamicsDrawerDirectionVertical) {
        boundary.size.width = (CGRectGetWidth(self.paneView.frame) + plus1);
        switch (state) {
            case MSDynamicsDrawerPaneStateClosed:
                boundary.size.height = ((CGRectGetHeight(self.paneView.frame) * 2.0) + self.paneStateOpenWideEdgeOffset + plus2);
                break;
            case MSDynamicsDrawerPaneStateOpen:
                boundary.size.height = ((CGRectGetHeight(self.paneView.frame) + self.openStateRevealWidth) + plus2);
                break;
            case MSDynamicsDrawerPaneStateOpenWide:
                boundary.size.height = ((CGRectGetHeight(self.paneView.frame) * 2.0) + self.paneStateOpenWideEdgeOffset + plus2);
                break;
        }
    }
    switch (direction) {
        case MSDynamicsDrawerDirectionRight:
            boundary.origin.x = ((CGRectGetWidth(self.paneView.frame) + plus1) - boundary.size.width);
            break;
        case MSDynamicsDrawerDirectionBottom:
            boundary.origin.y = ((CGRectGetHeight(self.paneView.frame) + plus1) - boundary.size.height);
            break;
        case MSDynamicsDrawerDirectionNone:
            boundary = CGRectZero;
            break;
        default:
            break;
    }
    return [UIBezierPath bezierPathWithRect:boundary];
```

I'm starting a new project and haven't noticed it, so I started pulling threads after you posted the issue. 
This is not a solution, and you'll have to add something in the code to know if you are using iOS8 or not.
Maybe someone more used to `UICollisionBehavior` could bring some light to what's wrong with these boundaries, I just played with the numbers to fit what seems to be a bug.

**Comment by kioqq** [comment] 2014-09-22 20:03
@lluisgerard thx u! This solution work's good for me.

I just set 0,0 :smile: 

```
boundary.origin = (CGPoint){0.0, 0.0};
```

**Comment by nfranke** [comment] 2014-12-09 15:14
None of these solutions seem to fix it for all versions of iOS on all devices with different gravity and elasticity settings. I can reproduce the slight bounce with all values. In fact, setting the gravity rather high will cause the system to visibly bounce forever.

**Comment by brentd** [comment] 2014-12-21 16:19
FWIW, following @lluisgerard's patch was a good enough workaround for me -- combined with using the fade styler and a black background on the `MSDynamicsDrawerViewController` view. If the background is black, the 1pt shift that can still occur on other versions of iOS (or if the drawer is on the right side, I've found) is barely noticeable on an actual device because it's lost against the screen's black edge.

Here's how to apply the fade styler:

``` objc
[drawViewController addStyler:[MSDynamicsDrawerFadeStyler styler] forDirection:(MSDynamicsDrawerDirectionLeft | MSDynamicsDrawerDirectionRight)];
```

Certainly not ideal, but we're here to ship software, yes? :)

**Closed as completed** 2022-01-17 21:55 UTC
